### ISSUE TITLE
MOM 04-02-2021

### ISSUE THREAD

**Issue by QuirinEcker** [htl-leonding-project/leo-iot#32]
- Branches mehr zusammenfügen
- Verantwortungsmatrix genauer machen
- Systemarchitektur in eigenes Entwurfsdokument
- Entwurfs Dokument
-- Was macht das Backend
-- Was machen die einzelnen Teilberreiche
- Generell aufschreiben was ist zu tun
- Kleine Aufgaben zerteilen
- Einzelne Issues genauer deffinieren und zuteilen
- Grob bestimmen was zu tun ist
- Dann fragen ob wir das richtig machen
- Backlog für eine issue
- leo-iot deprectated (ist schon in description drinnen)
- nicht definiert 
-- was ist zu tun
-- wer macht es
- Funktioniert das 3d Modell?
- Funktioniert das Dashboard?
- Einzelne Seiten herrichten
- Mit bit.ly
- Es sollte was laufähiges sein auf Master sein
- bis 18.1 lauffähig machen. (--> Milestone P)
- nicht ersichtlich was die Aufgabe ist.
- update System Architecture (has to be detailed)
- Projekt Handbuch
- Projekt specificatio
- Design Specification
- Organisation Handbook
- Verlinkung bei about

**Comment by PhilippEdlinger** [comment]
18.02 sprint review
jeder sollte sich eigens issues mit den details inkl. commits, 
https://2021-3ahif-syp.github.io/02-project-restaurant-management-system/
projekt handbuch erstellen 
verantwortungsmatrix ändern 
systemarchitektur eigenes bild
die teilbereiche der Verantwortungsmatrix defenieren
beispiels scrum product erstellen backlog 
jedem eine klar defenierte aufgabe geben
dem prof. die wichtigen links schicken
alle branches bis zum 18.02 mergen
handbuch  (email, eintrittpspunkt ind  project, )
alles verlinken wenn möglich 
system architectur entwursdokumnet
zentraleseite
projespec, designspec, organisationla handbook
in github auf das Zahnrad link verlinken

**Comment by PhilippEdlinger** [comment]
https://2021-3ahif-syp.github.io/02-project-restaurant-management-system/
